name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r libs.txt

    - name: Get server IP address
      run: |
        ip addr show eth0 | grep 'inet ' | awk '{ print $2 }' | cut -f1 -d'/'

    - name: Run script
      run: python main.py
